### ISSUE TITLE
What is "api.player"?

### ISSUE THREAD

**Issue by JnCrMx** [TheRedMajora/BotW#1]
What is "api.player.model.ModelPlayerAPI" and "api.player.render.RenderPlayerAPI"?

`import api.player.model.ModelPlayerAPI;
import api.player.render.RenderPlayerAPI;`
from com.theredmajora.botw.BOTW ([https://github.com/TheRedMajora/BotW/blob/master/src/main/java/com/theredmajora/botw/BOTW.java](url))

If I did something wrong, tell me! I´m new on GitHub.

**Comment by TheRedMajora** [comment]
Seems like you closed this before I could respond.
Well, those are the classes used by the api called RenderPlayerAPI

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1283669-render-player-api

If you have more questions feel free to ask, I'll see to it whenever I have time.
